# Generated by Django 2.2.6 on 2019-10-10 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('oper', models.CharField(max_length=250)),
                ('sitename', models.CharField(max_length=500)),
                ('descr', models.CharField(max_length=9000)),
                ('site_logo', models.FileField(upload_to='')),
                ('site_map', models.FileField(default='', upload_to='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('periode', models.CharField(max_length=300)),
                ('coordx', models.FloatField()),
                ('coordy', models.FloatField()),
                ('paleol', models.CharField(max_length=300)),
                ('bronze', models.CharField(max_length=30)),
                ('discovered', models.IntegerField()),
                ('iron', models.CharField(max_length=30)),
                ('mesol', models.CharField(max_length=30)),
                ('middle_age', models.CharField(max_length=30)),
                ('neol1', models.CharField(max_length=30)),
                ('neol2', models.CharField(max_length=30)),
                ('neol3', models.CharField(max_length=30)),
                ('passport', models.CharField(max_length=20)),
                ('topo', models.FileField(default='', upload_to='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
