# Generated by Django 2.2.4 on 2019-10-11 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staticmap',
            fields=[
                ('id_map', models.IntegerField(primary_key=True, serialize=False)),
                ('mapname', models.CharField(max_length=250)),
                ('mapfile', models.FileField(upload_to='')),
                ('autor', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sites',
            options={'ordering': ('sitename',)},
        ),
        migrations.CreateModel(
            name='Mobiliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_nom', models.CharField(max_length=250)),
                ('mob_logo', models.FileField(default='', upload_to='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touim.Sites')),
            ],
        ),
        migrations.CreateModel(
            name='Biblio',
            fields=[
                ('id_biblio', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('bib_logo', models.FileField(upload_to='')),
                ('tip', models.CharField(max_length=50)),
                ('coll', models.CharField(default='', max_length=250)),
                ('edition', models.CharField(default='', max_length=250)),
                ('pages', models.CharField(default='', max_length=30)),
                ('site', models.ManyToManyField(to='touim.Sites')),
            ],
            options={
                'ordering': ('id_biblio',),
            },
        ),
        migrations.CreateModel(
            name='Admini',
            fields=[
                ('id_admini', models.IntegerField(primary_key=True, serialize=False)),
                ('categ', models.CharField(max_length=250)),
                ('vid', models.CharField(max_length=100)),
                ('vid_comm', models.CharField(max_length=250)),
                ('utilisation', models.CharField(max_length=250)),
                ('herit', models.CharField(max_length=50)),
                ('infor', models.CharField(default='', max_length=9000)),
                ('descr', models.CharField(default='', max_length=9000)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touim.Sites')),
            ],
        ),
    ]
