# Generated by Django 3.2.2 on 2021-05-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiliers',
            old_name='mob_logo',
            new_name='mob_img',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='paleol',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='site_logo',
            new_name='site_img',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='bronze',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='coordx',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='coordy',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='discovered',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='infor',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='mesol',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='middle_age',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='neol1',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='neol2',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='neol3',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='periode',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='topo',
        ),
    ]
