# Generated by Django 2.2.6 on 2019-10-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0003_mobiliers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='site_logo',
            field=models.FileField(default='notfound.jpg', upload_to='profile_pics'),
        ),
    ]
