# Generated by Django 2.2.6 on 2019-10-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0004_auto_20191013_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='topo',
            field=models.FileField(default='notfound.jpg', upload_to='profile_pics'),
        ),
    ]
