# Generated by Django 2.2.6 on 2019-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0006_auto_20191014_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='site_logo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
