# Generated by Django 2.2.6 on 2019-10-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0007_auto_20191015_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='site_logo',
            field=models.FileField(default='Mickey_Mouse.png', upload_to='media/'),
        ),
    ]
