# Generated by Django 2.2.6 on 2019-10-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0008_auto_20191016_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='topo',
            field=models.FileField(default='v1_topo.png', upload_to=''),
        ),
    ]
