# Generated by Django 2.2.6 on 2019-10-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0009_auto_20191020_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='infor',
            field=models.CharField(default='', max_length=9000),
        ),
        migrations.AlterField(
            model_name='sites',
            name='descr',
            field=models.CharField(default='', max_length=9000),
        ),
    ]
