# Generated by Django 2.2.6 on 2019-10-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0010_auto_20191021_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='site_map',
        ),
    ]
