# Generated by Django 2.2.6 on 2019-10-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0011_remove_sites_site_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='is_favorite',
        ),
    ]
