# Generated by Django 2.2.6 on 2019-10-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0012_remove_sites_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiliers',
            name='is_favorite',
        ),
    ]
