# Generated by Django 2.2.6 on 2019-10-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0016_auto_20191023_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='site_logo',
            field=models.FileField(default='Mickey_Mouse.png', upload_to=''),
        ),
    ]
