# Generated by Django 2.2.6 on 2019-10-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0017_auto_20191024_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiliers',
            name='mob_logo',
            field=models.FileField(default='Mickey_Mouse.png', upload_to=''),
        ),
    ]
