# Generated by Django 2.2.6 on 2019-10-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0018_auto_20191024_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiliers',
            name='mob_logo',
            field=models.FileField(default='pasdimage.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site_logo',
            field=models.FileField(default='pasdimage.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sites',
            name='topo',
            field=models.FileField(default='pasdimage.png', upload_to=''),
        ),
    ]
