# Generated by Django 2.2.6 on 2019-10-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0019_auto_20191024_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id_img', models.IntegerField(primary_key=True, serialize=False)),
                ('imgname', models.CharField(max_length=250)),
                ('imgfile', models.FileField(default='', upload_to='')),
                ('author', models.CharField(max_length=250)),
            ],
        ),
    ]
